# Generated by Django 3.2.5 on 2021-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='is_sys_defined',
            field=models.BooleanField(default=False),
        ),
    ]
