# Generated by Django 3.2.5 on 2021-07-08 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdm_app', '0002_alter_normaluser_is_sys_defined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='teammanager',
            name='team_title',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team_title',
        ),
        migrations.AddField(
            model_name='deadline',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='gdm_app.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deadline',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('IP', 'In Progress'), ('M', 'Missed')], default='IP', max_length=2),
        ),
        migrations.AddField(
            model_name='deadline',
            name='tasks',
            field=models.ManyToManyField(to='gdm_app.Task'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_deadline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_deadline', to='gdm_app.deadline'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='Project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gdm_app.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='completion_status',
            field=models.CharField(choices=[('NC', 'Not Completed'), ('CP', 'Check Pending'), ('C', 'Completed'), ('F', 'Failed')], default='NC', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gdm_app.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='gdm_app.teammanager'),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gdm_app.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammanager',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='gdm_app.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gdm_app.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gdm_app.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
