# Generated by Django 3.2.5 on 2021-07-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdm_app', '0003_auto_20210708_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_deadline', to='gdm_app.deadline'),
        ),
    ]
