# Generated by Django 3.2.5 on 2021-07-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdm_app', '0006_rename_project_projectmanager_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.AddField(
            model_name='task',
            name='deadlines',
            field=models.ManyToManyField(to='gdm_app.Deadline'),
        ),
    ]
